STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "been", "being", "but", "by",
    "can", "could", "did", "do", "does", "doing", "done", "for", "from", "had",
    "has", "have", "having", "he", "her", "here", "hers", "him", "his", "how",
    "i", "if", "in", "into", "is", "it", "its", "just", "like", "make", "me",
    "might", "more", "most", "my", "no", "not", "now", "of", "on", "one", "only",
    "or", "our", "out", "own", "really", "said", "same", "she", "should", "so",
    "some", "such", "than", "that", "the", "their", "them", "then", "there",
    "these", "they", "this", "those", "through", "to", "too", "up", "us",
    "very", "was", "we", "well", "were", "what", "when", "where", "which",
    "while", "who", "will", "with", "would", "you", "your", "also", "about",
    "after", "all", "any", "because", "before", "between", "both", "each",
    "even", "few", "first", "get", "go", "going", "good", "got", "however",
    "know", "last", "like", "long", "made", "many", "may", "much", "must",
    "need", "new", "next", "nothing", "often", "old", "once", "only", "other",
    "over", "own", "part", "people", "put", "right", "same", "say", "see", "set",
    "several", "show", "since", "still", "such", "take", "thing", "think",
    "though", "three", "time", "two", "under", "upon", "use", "want", "way",
    "well", "work", "year", "yet", "use", "used", "using", "showed", "shown",
    "gives", "given", "means", "within", "without", "became", "become", "makes",
    "based", "approach", "result", "results", "paper", "study", "work",
    "research", "method", "methods", "model", "data", "system", "performance",
    "problem", "propose", "proposed", "present", "presented", "provide",
    "provided", "high", "low", "large", "small", "different", "various",
    "number", "number", "case", "point", "term", "field", "area", "type",
    "level", "group", "et", "al", "ie", "eg", "etc", "vs", "via", "per", "cc",
    "b", "c", "d", "e", "f", "g", "h", "j", "k", "l", "m", "n", "o", "p",
    "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "one", "two", "three",
    "four", "five", "six", "seven", "eight", "nine", "ten", "zero", "first",
    "second", "third", "fourth", "fifth", "sixth", "seventh", "eighth", "ninth",
    "tenth", "many", "several", "various", "multiple", "single", "double",
    "however", "therefore", "thus", "hence", "accordingly", "consequently",
    "moreover", "furthermore", "additionally", "besides", "meanwhile",
    "nevertheless", "nonetheless", "otherwise", "instead", "rather", "whereas",
    "while", "although", "though", "despite", "except", "save", "since",
    "because", "as", "lest", "provided", "unless", "until", "when", "whenever",
    "where", "wherever", "whether", "which", "who", "whom", "whose", "whatever",
    "whichever", "whoever", "whomever", "can", "could", "may", "might", "must",
    "shall", "should", "will", "would", "do", "does", "did", "have", "has",
    "had", "having", "be", "been", "being", "get", "gets", "got", "getting",
    "make", "makes", "made", "making", "use", "uses", "used", "using", "show",
    "shows", "showed", "showing", "shown", "give", "gives", "gave", "giving",
    "done", "see", "sees", "saw", "seeing", "find", "finds", "found", "finding",
    "tell", "tells", "told", "telling", "ask", "asks", "asked", "asking",
    "become", "becomes", "became", "becoming", "leave", "leaves", "left",
    "leaving", "put", "puts", "putting", "keep", "keeps", "kept", "let", "lets",
    "setting", "begin", "begins", "began", "beginning", "seem", "seems",
    "seemed", "seeming", "help", "helps", "helped", "helping", "show", "shows",
    "showed", "try", "tries", "tried", "trying", "offer", "offers", "offered",
    "offering", "consider", "considers", "considered", "considering", "appear",
    "appears", "appeared", "appearing", "believe", "believes", "believed",
    "believing", "belong", "belongs", "belonged", "belonging", "form", "forms",
    "formed", "forming", "contain", "contains", "contained", "containing",
    "describe", "describes", "described", "describing", "exist", "exists",
    "existed", "existing", "follow", "follows", "followed", "following",
    "receive", "receives", "received", "receiving", "report", "reports",
    "reported", "reporting", "decide", "decides", "decided", "deciding",
    "require", "requires", "required", "requiring", "develop", "develops",
    "developed", "developing", "provide", "provides", "provided", "providing",
    "use", "uses", "used", "using", "include", "includes", "included",
    "including", "continue", "continues", "continued", "continuing",
    "increase", "increases", "increased", "increasing", "allow", "allows",
    "allowed", "allowing", "affect", "affects", "affected", "affecting",
    "create", "creates", "created", "creating", "express", "expresses",
    "expressed", "expressing", "maintain", "maintains", "maintained",
    "maintaining", "produce", "produces", "produced", "producing", "reduce",
    "reduces", "reduced", "reducing", "remove", "removes", "removed",
    "removing", "require", "requires", "required", "requiring", "explain",
    "explains", "explained", "explaining", "achieve", "achieves", "achieved",
    "achieving", "apply", "applies", "applied", "applying", "argue", "argues",
    "argued", "arguing", "assume", "assumes", "assumed", "assuming", "cause",
    "causes", "caused", "causing", "choose", "chooses", "chose", "chosen",
    "choosing", "classify", "classifies", "classified", "classifying",
    "compare", "compares", "compared", "comparing", "conclude", "concludes",
    "concluded", "concluding", "conduct", "conducts", "conducted",
    "conducting", "consist", "consists", "consisted", "consisting", "define",
    "defines", "defined", "defining", "demonstrate", "demonstrates",
    "demonstrated", "demonstrating", "depend", "depends", "depended",
    "depending", "derive", "derives", "derived", "deriving", "determine",
    "determines", "determined", "determining", "detect", "detects", "detected",
    "detecting", "discuss", "discusses", "discussed", "discussing",
    "distinguish", "distinguishes", "distinguished", "distinguishing",
    "eliminate", "eliminates", "eliminated", "eliminating", "establish",
    "establishes", "established", "establishing", "estimate", "estimates",
    "estimated", "estimating", "evaluate", "evaluates", "evaluated",
    "evaluating", "examine", "examines", "examined", "examining", "extend",
    "extends", "extended", "extending", "focus", "focuses", "focused",
    "focusing", "generate", "generates", "generated", "generating", "identify",
    "identifies", "identified", "identifying", "illustrate", "illustrates",
    "illustrated", "illustrating", "imply", "implies", "implied", "implying",
    "indicate", "indicates", "indicated", "indicating", "influence",
    "influences", "influenced", "influencing", "interpret", "interprets",
    "interpreted", "interpreting", "investigate", "investigates",
    "investigated", "investigating", "measure", "measures", "measured",
    "measuring", "obtain", "obtains", "obtained", "obtaining", "operate",
    "operates", "operated", "operating", "organize", "organizes", "organized",
    "organizing", "perform", "performs", "performed", "performing", "predict",
    "predicts", "predicted", "predicting", "recognize", "recognizes",
    "recognized", "recognizing", "relate", "relates", "related", "relating",
    "reveal", "reveals", "revealed", "revealing", "select", "selects",
    "selected", "selecting", "separate", "separates", "separated",
    "separating", "signal", "signals", "signaled", "signaling", "specify",
    "specifies", "specified", "specifying", "suggest", "suggests", "suggested",
    "suggesting", "support", "supports", "supported", "supporting", "treat",
    "treats", "treated", "treating", "utilize", "utilizes", "utilized",
    "utilizing", "validate", "validates", "validated", "validating",
}